from git.util import LazyMixin
from typing import Any, Optional

class Object(LazyMixin):
    NULL_HEX_SHA: Any = ...
    NULL_BIN_SHA: Any = ...
    TYPES: Any = ...
    type: Any = ...
    repo: Any = ...
    binsha: Any = ...
    def __init__(self, repo: Any, binsha: Any) -> None: ...
    @classmethod
    def new(cls, repo: Any, id: Any): ...
    @classmethod
    def new_from_sha(cls, repo: Any, sha1: Any): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
    def __hash__(self) -> Any: ...
    @property
    def hexsha(self): ...
    @property
    def data_stream(self): ...
    def stream_data(self, ostream: Any): ...

class IndexObject(Object):
    mode: Any = ...
    path: Any = ...
    def __init__(self, repo: Any, binsha: Any, mode: Optional[Any] = ..., path: Optional[Any] = ...) -> None: ...
    def __hash__(self) -> Any: ...
    @property
    def name(self): ...
    @property
    def abspath(self): ...
