from typing import Any

def tree_to_stream(entries: Any, write: Any) -> None: ...
def tree_entries_from_data(data: Any): ...
def traverse_trees_recursive(odb: Any, tree_shas: Any, path_prefix: Any): ...
def traverse_tree_recursive(odb: Any, tree_sha: Any, path_prefix: Any): ...
