from gitdb.db.base import CompoundDB
from typing import Any

class ReferenceDB(CompoundDB):
    ObjectDBCls: Any = ...
    def __init__(self, ref_file: Any) -> None: ...
    def update_cache(self, force: bool = ...): ...
