from gitdb.util import to_hex_sha as to_hex_sha

class ODBError(Exception): ...
class InvalidDBRoot(ODBError): ...
class BadObject(ODBError): ...
class BadName(ODBError): ...
class ParseError(ODBError): ...
class AmbiguousObjectName(ODBError): ...
class BadObjectType(ODBError): ...
class UnsupportedOperation(ODBError): ...
