from gitdb.exc import *
from git.compat import safe_decode as safe_decode
from typing import Any, Optional

class GitError(Exception): ...
class InvalidGitRepositoryError(GitError): ...
class WorkTreeRepositoryUnsupported(InvalidGitRepositoryError): ...
class NoSuchPathError(GitError, OSError): ...

class CommandError(GitError):
    command: Any = ...
    status: Any = ...
    stdout: Any = ...
    stderr: Any = ...
    def __init__(self, command: Any, status: Optional[Any] = ..., stderr: Optional[Any] = ..., stdout: Optional[Any] = ...) -> None: ...

class GitCommandNotFound(CommandError):
    def __init__(self, command: Any, cause: Any) -> None: ...

class GitCommandError(CommandError):
    def __init__(self, command: Any, status: Any, stderr: Optional[Any] = ..., stdout: Optional[Any] = ...) -> None: ...

class CheckoutError(GitError):
    failed_files: Any = ...
    failed_reasons: Any = ...
    valid_files: Any = ...
    def __init__(self, message: Any, failed_files: Any, valid_files: Any, failed_reasons: Any) -> None: ...

class CacheError(GitError): ...
class UnmergedEntriesError(CacheError): ...

class HookExecutionError(CommandError):
    def __init__(self, command: Any, status: Any, stderr: Optional[Any] = ..., stdout: Optional[Any] = ...) -> None: ...

class RepositoryDirtyError(GitError):
    repo: Any = ...
    message: Any = ...
    def __init__(self, repo: Any, message: Any) -> None: ...
